### ISSUE TITLE
The Bad Texture Error

### ISSUE THREAD

**Issue by callowaysutton** [jhmaloney/GP-Mods#5]
I've been running into this issue constantly, do any of you guys know where this issue could originate from? Is it in the runtime or is it an issue with the actual bootstrapper?

I'm running the latest download from the website and the only thing I've modified is the project stage ratio (made it 16:9 instead of 16:10).

**Comment by Spiralo-Idioide** [comment]
It doesn't seem to come directly to come from the runtime since the Bad Texture error is not coded in the runtime. It is still possible to find it in the executables (I did it with Notepad ++).
![](https://framapic.org/dmumnrMLwKfy/RCbRkUDKshhi.png)

But I didn't encounter this error for a long time and I don't remember if it happens in a particular context. 
I'm currently trying to get the error, I'll tell you if I find anything.

**Comment by Spiralo-Idioide** [comment]
Also, if you have any specific project...

**Comment by callowaysutton** [comment]
I never could get around to finishing this small leaderboard because of the bad texture error constantly popping up and deleting all my previous work. Could it be because I'm using large bitmaps?

I was able to reproduce it by leaving this project running for ~20 seconds, stopping it, and then trying to save it to a new location.


[Leaderboards.zip](https://github.com/jhmaloney/GP-Mods/files/4302402/Leaderboards.zip)
(Just change extension from .zip to .gpp)

Also reproducible by going fullscreen or making the Stage have greater than a 1920x1080 resolution.

**Comment by Spiralo-Idioide** [comment]
It seems to come (at least partially) from the takeThumbmail method.
I still don't know why.

**Comment by Spiralo-Idioide** [comment]
Also, if anytime you see an instance that does have a costume but the costume is not shown in the instance page, press clear as fast as you can. 
Changing fullscreen or windows size is also a bad idea after saving a project.

**Comment by Spiralo-Idioide** [comment]
The bug is without a doubt linked with the instances icons disappearing. But the problem is that this disappearance might happens at multiple points of the execution of the save function, the takeThumbmail and loadPage methods
I'll try to go deeper and I'll tell you about it

**Comment by callowaysutton** [comment]
Well that's good, if thats the case then there might be a way to fix this issue in the runtime. I was worried it could've been an issue with the actual interpreter

**Comment by Spiralo-Idioide** [comment]
I'm currently trying to make an alternative way of saving projects that would be folder based instead of file based. Every class created by the user would have his own file for methods and scripts and images would be stored as files and not as GP object in the .gpod file. But it would still be possible to make it a file by zipping it.

**Comment by callowaysutton** [comment]
Would that not interfere with the app maker? It uses the zipped .gpp file to embed the project

**Comment by Spiralo-Idioide** [comment]
I think I found a possible workaround fix by creating a temporary class that is deleted after the project is saved.

**Comment by Spiralo-Idioide** [comment]
Ok there is something even easier, there is a block ( clearLibrary ) that just solve the problem. 
I'm creating the pull request
